apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dervoeti/testing'
    targetRevision: main
    path: postgresql
    plugin:
      name: argocd-vals-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            auth:
              username: foo
              password: ref+azurekeyvault://stackable/bar
              database: foo
  destination:
    server: 'https://kubernetes.default.svc'

