apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dervoeti/testing'
    targetRevision: main
    path: test
    plugin:
      name: argocd-vals-plugin
  destination:
    server: 'https://kubernetes.default.svc'
